import Enum from './Enum';

module.exports = Enum([
  'IP_ACCEPTED',
  'IP_INBOUND',
  'IIP_INBOUND',
  'INITIALIZE',
  'IP_REQUESTED',
  'IP_AVAILABLE',
  'STATUS_UPDATE',
  'ACTIVATION_REQUEST',
  'COMMENCE',
  'PORT_CLOSURE',
  'PROCESS_COMPLETING',
  'ERROR'
]);
